HotkeyName := [],                   ;Displayed name of the hotkey
HotkeySub := [],                    ;Subroute affix 
HotkeyDescription := [],            ;Description of what each hotkeys do / any text
HotkeySettings := [],               ;List of settings that will be shown in the Settings tab
HotkeySettingsDescription := [],    ;Description of what the settings do
HotkeyPrev := [],                   ;Internal
HotkeyGlobal := [],                 ;Defines if the hotkey will be active in all profiles
HotkeyShift := [],                  ;Defines if the hotkey has a Shift subroute
HotkeyAlt := [],                    ;Defines if the hotkey has a Alt subroute
HotkeyCtrlAlt := [],                ;Defines if the hotkey has a CtrlAlt subroute
HotkeyCtrlShift := [],              ;Defines if the hotkey has a CtrlShift subroute
HotkeyTick := [],                   ;Defines if the hotkey has a Tick subroute that will be called every tick